nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['*']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_methods: ['*']
            allow_headers: ['*']
            max_age: 3600