version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    environment:
      MARIADB_DB: ${MARIADB_DB:weatherstation-app}
      # You should definitely change the password in production
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:root}
      MARIADB_USER: ${MARIADB_USER:root}
    volumes:
      - database_data:/var/lib/mariadb/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
